name: 'Trabalho de conclusão - Integração Continua'

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '30 21 * * *'

jobs:
  teste-unitario:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: 24.x

      - name: Instalando Dependências
        run: npm i -g

      - name: Instalando o Mocha
        run: npm i mocha
      
      - name: Instalar Mochawesome
        run: npm i mochawesome

      - name: Execultar e reportar
        run: npx mocha --reporter mochawesome
      
      - name: Salvando relatórios
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./mochawesome-report
          name: Relatório de Testes Unitários